#!/bin/bash


#install
apt update && apt upgrade
apt install neofetch -y
apt install python3 python3-pip git
clear
Gren="\033[0;32m"
figlet -f slant "AriScTunnel" | lolcat
neofetch
echo -e "  ${Gren} Information System${NC}"
echo -e "  ${Gren}---------------------------------------${NC}"
echo -e "  ${Gren}   Terimakasih  Telah  Menggunakan${NC}"
echo -e "  ${Gren}    Script Creadit By ARISCTUNNEL V3${NC}"
echo -e "  ${Gren}---------------------------------------${NC}"
echo -e ""
